name: Ta.io
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbf9'
    - '#8e8783'
    - '#1c1618'
    - '#d54644'
    - '#005c7e'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
