name: Ta.io
favicon: null
layout_spectrum: 0.8913762681186199
typography_spectrum: 0.5474356347694993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3056528845336288
  lightness: 0.9985418275464326
  saturation: 0.6729487674310803
  rhythmicContrast: 0.43907762109301984
purpose: []
